### ISSUE TITLE
Does not work on low temperatures, always show -127C

### ISSUE THREAD

**Issue by Nalorokk** [milesburton/Arduino-Temperature-Control-Library#27] opened 2015-02-09 00:13 UTC

**Comment by milesburton** [comment] 2015-02-09 10:07
Can you confirm which version (commit) you are using from Git. This was actually recently resolved

**Comment by Nalorokk** [comment] 2015-02-09 10:49
Still exists for me in latest commit 146cfdd2d7

**Comment by RobTillaart** [comment] 2015-07-04 13:13
@Nalorokk 
Does this problem still exist? otherwise this issue can be closed.

**Comment by milesburton** [comment] 2015-07-08 10:28
I believe this is actually still outstanding. https://github.com/milesburton/Arduino-Temperature-Control-Library/tree/tommi-tuovila-temperature-fix resolved the issue but I don't believe it was ever confirmed by the author so I opted to avoid merging.

Are you able to test this in your setup and let us know if it works. If it does, it'll be quick merge

**Comment by milesburton** [comment] 2015-09-23 06:30
Closing, assuming not a problem

**Closed by milesburton** 2015-09-23 06:30 UTC

**Comment by rubberduck203** [comment] 2017-10-17 00:10
I know it's an old issue, but I'm actually experiencing this problem with a MAX31820.
Does anyone remember the cause or solution?

**Comment by rubberduck203** [comment] 2017-10-17 00:35
This happens if you wire VDD and GND backwards.
The pinout in the datasheet for the MAX31820 is wrong.

<img width="711" alt="screen shot 2017-10-16 at 8 31 19 pm" src="https://user-images.githubusercontent.com/2716800/31641271-8169fa5e-b2b1-11e7-95a5-9f3287b72cee.png">
