### ISSUE TITLE
Function for isConversionComplete not integrated

### ISSUE THREAD

**Issue by muldereric** [milesburton/Arduino-Temperature-Control-Library#26] opened 2015-01-31 11:14 UTC
The library interface class has a function called isConversionComplete. However this function is not implemented in the library itself, hence it does not compile when used.

**Comment by RobTillaart** [comment] 2015-02-03 09:17
Duplicate of #12  (solution can be found there)

**Comment by RobTillaart** [comment] 2015-07-04 13:14
@milesburton 
Can be closed

**Closed** 2015-07-08 10:27 UTC
