### ISSUE TITLE
Example of persistent device order?

### ISSUE THREAD

**Issue by dsjstc** [milesburton/Arduino-Temperature-Control-Library#78] opened 2017-05-03 20:17 UTC
The various ByIndex functions are susceptible to reordering if any devices are added or removed from the bus, [as described in this issue](https://github.com/milesburton/Arduino-Temperature-Control-Library/issues/76).

I think it's a common use case to want a few temperatures in an ordered array, where the order can survive changes to the bus.  If it's not common enough to bake into the library itself, it'd be great to have an example of that functionality!

**Comment by RobTillaart** [comment] 2017-12-22 13:40
@milesburton 
Can be closed as it is more or less a duplicate of #76

**Closed** 2017-12-22 13:44 UTC
